### ISSUE TITLE
刷新jwt机制问题

### ISSUE THREAD

**Issue by way1110** [hyrepo/jwt-demo#1]
1. 如果jwt设置的过期时间很短,比如10分钟,我在10分钟内都没有操作,也就获取不到新的jwt token了

**Comment by hyrepo** [comment]
@way1110 是的，这个和cookie的过期/刷新机制很相似，因为如果JWT不会过期的话别人获取到token就能很容易使用，即使这个token不属于自己。

**Comment by caidingnu** [comment]
登录成功之后，用户获取的token保存在前端哪里？每次发送请求都要获取前端存储的token携带吗

**Comment by hyrepo** [comment]
> 登录成功之后，用户获取的token保存在前端哪里？每次发送请求都要获取前端存储的token携带吗

是的，每次都要携带，对于保存的地方没限制
